sudo: required
services: [ docker ]
language: perl
perl: "5.18"
env:
  global:
    - PKG_REPOTYPE=community
    # packagecloud API token for citus-bot
    - secure: "DrgnMSsX/XvMZltIvnE9VTGFRVDWfLafTdJwjd//vgLZ8PDNJ/UHm7Vr7dBoNIR0LytMnBgGWRfz6oi5HNgNLc2GnTfv4muyjK8i2OTmvs4ALKBoxiI888+nhh6jhf9WYvCKGNolTspxP3dgVB9B2NiGCyKBN2hCzts59fqtGED+kSE0Bda/pBnDHml7IMMHwdXB3V9KNOdD42TE8Bf7B/XpI69JZfaYrBqGYidVaInqaVEFjNOmkndLEXl5cf82YCWAYCJ/VlKgcg5Zi38kpiYn7ZjQ6QuVibbxOWG5hSQym6UYy/5HieEajo6aaamaun5ATcUMfRNtrQBGiwAkI0lPjrx8TPE00EfFJ6lryUa3eABs9dntI3veZPQdh3w8AHEbUiRb0VVJ934STlKllRskpMmE1MT7VqRnYHAsVPrY0J2sXnmAGPHf1B1LgJE3mljIVJVsTHJc/GaRmXQuUxyrU32BkN1Ie92gZjaDeVddFiQh0KND0HMtF0CmbPy5t8tRQnMVVcIKLQUfMF8ELGnqw+v5rxBho8w+mZ4Jg6MR1Z0wIs63+4/yHLmD4l/09AA6kLZVEuJYqwV71nEL5QI561S2lDTOh8c0toe/GMkmdO+9aQ1aASjixkuWnDj8Ok22fWFkOojt861FXGOszyT2DbSJweFrKPs7Cv8XV2M="
    # GitHub ("Packaging") API token for citus-bot
    - secure: "zb6AHEUEvpCnWb4zRTsWTWVmMWNHkzz4c+UUgABaXYysJHCfBNiu5X4Da/jusCPY9GH4XFX8GPCiR69ZKw/LDnzHgXoH2pmda02CZM6SHjRGd0MrlBl0hF8YbHiBFi6/nH7kF0ODX+SepfJlFq8LQq6HVONz6QQl0FW0Rg1qnNaDMMi6L9NBBSDyuYCUdY05lgNeIyG8LyIErvlNA8U86VxOHp/KKbNaNx0Cs/tpDWNeW1v1rxa6EXtt8pxyc4u09V9csyFcglizkWEi98aqBTqyCa4hgIK3anog51vAg997cPOUu+ENUpwsio2JMorXalzNszBtpbO9u15+hLRHAoSL56hRdar3fTCuyyXpKapyNZ5Xxa8bYmgLDSJ2lS3zDl6fUfJWVqfzDWx1BuYVGjmJquYMVGKDiBu6iiOx7M/L8Kwof/ioe1LWro92a+S2KKgmXJfxNm4//F2EK+n++GNMZzOsfW+HSVhZ5sXt/tN9eOGmRQ4jWOZK7ycdpB+zMtxYDur/D46oLGAJhY88YqJaBbx0Jk0EMzSfM1eSoGcXEfLfwzGTm3MFnG/IJ3BPW1pkf5s2gMofUssGFitqnDZ7wlexrwA6qPMPIafW+yn5m4wwQwAxk20Y/kOREKHYDP6X6AbQNmfUk93/djYLjd/gGYLS3xvkNOLBWq2CCD8="
    # passphrase for packaging gpg secret key
    - secure: "pZmrxStWj0vXaG/YAyJORvxfaKQHvr+O+66yjFF52gQTVd2zNb83Mn4zDLNqMwU3nkXEKYuFbpXKbDSMX9zNbE7W/w1ARSa8MVXnMVM3jbj+OCaBu7fyVrA0tvT3EZkMh943paTRcSyPSzd61P3CNOkcY1RycDHBbJtNrzSdUbdAy6//TWgNxC66dxSeHASRJIIs49caxQssMMSGRgC5aGH4KLU5eSdP3wnWDEHr+aLqaI2DF2W3lNMI0WJwtGN6cLEYzAsA3BkoPoYRFDd4jjTpolVdrFBXRaT1EIg0FXjsvjyFrQfQLBIqvSx42H5w4rCIYoKYYgRgCKDATLK8XxPbFsgPKLVSHFD6t9ebuYacYxS20oMakkqj5e98qMIWe2vkm+V9YNeADIlhYT+NsF9Kug2B6pLK+U+Hhj6TldFpP18snPXttRKzsg9QrGbnBUVq2wv60U7/3pWs+T3tpr9bIFyaUYbRRAwl/hv2hVkFiSdsiLB6tJphbILB7EDKBCu1iK9PC9tlYoGrqptRxj6bmlawOvcnEKRtoPNJ9eyrvHPDd8FmmW6xWbq89zJ97Ztl7VR8CzNePqvG9vwdtJigXovuXfzu4CHX+jOt3jvllB6rMprsK5r++qBzh1SS24sYqo/APtUfoYdkleWhC+tSuhbucZb2yGUCMo/ZhDo="
    # Docker Hub URL to trigger new nightly image
    - secure: "A3mqytw2Tq/jSBYgBgMrP3sSHXhkRXMeHmsVlsrzrzgnQskJ62c+QbGMomHY71y8JSJWEWsmCCLBuayF9TwMVnbiELGQFSxX2Aw7sy3wNunk6rNKs166od3K0d9YctIBrqcBm25YUOby4FlYAluxipix4gqq8JayPkP4n3x+it9hyCGZL6WYhreEfIkmH2sISbjGZJ5PggsymlAQdBepvQRuBQTNysNFySw9ENme1tqgf3eiG/m9bvghkVphJwrkfFyC+LauhQGopjq5rXTR2yvB7zlj4LYAP65qtRQrkYOax0w5qpy4StxgsP5Q8JnW8qk+JM5lwLE8worMcYt8I6epclWOl4jkhCraIGm4XGOFzdcs/W2fBYeI9UFJBaPgt9RoxsSs8m6ER6ivDyaFkZ72gMwViogZnf5VABXoZ8tgaxYHfaT89OW2/X4x9V6ONv7jWy3xvdNUYqiDqHeWZSjMC+1JqhCEgMu23sL1u+gMXbCYSFq2dIh4pVRyK2H/StTHDP4teHlA2+OCFkfL/eQ2K0QunjPZxPU2+/V+zlUNWI4pEMV92JVQtjMZMcrDCS1DATXaasHpgphCexFEDqQwwKQoMh5j17nUBHjYxKqle5akakd/ShSi3F02uE3FGbIMSaYSreXdSjbzK8bkFU6q5rn0Fem0w20pcVyYPV8="
  matrix:
    - TARGET_PLATFORM=el/6
    - TARGET_PLATFORM=ol/6
    - TARGET_PLATFORM=el/7
    - TARGET_PLATFORM=ol/7
    - TARGET_PLATFORM=el/8
    #  Below commented out, because packagecloud does not support ol/8 packages yet.
    #- TARGET_PLATFORM=ol/8
    - TARGET_PLATFORM=debian/buster
    - TARGET_PLATFORM=debian/stretch
    - TARGET_PLATFORM=ubuntu/bionic
    - TARGET_PLATFORM=ubuntu/xenial
    - TARGET_PLATFORM=ubuntu/focal
before_install:
  - git clone -b v0.7.21 --depth 1 https://github.com/citusdata/tools.git
  - sudo make -C tools install
  - export PACKAGING_SECRET_KEY="$(openssl aes-256-cbc -K $encrypted_a39e3f1ee8ba_key -iv $encrypted_a39e3f1ee8ba_iv -in signing_key.asc.enc -d | base64)"
install: true
script: build_new_release && build_new_nightly
deploy:
  - provider: packagecloud
    username: "citusdata"
    repository: $PKG_REPOTYPE
    token: $PACKAGECLOUD_API_TOKEN
    dist: $TARGET_PLATFORM
    skip_cleanup: true
    local-dir: "pkgs/releases"
    on:
      branch: "all-citus"
      condition: -d "pkgs/releases"
  - provider: packagecloud
    username: "citusdata"
    repository: "$PKG_REPOTYPE-nightlies"
    token: $PACKAGECLOUD_API_TOKEN
    dist: $TARGET_PLATFORM
    skip_cleanup: true
    local-dir: "pkgs/nightlies"
    on:
      branch: "all-citus"
      condition: -d "pkgs/nightlies"
after_deploy: trigger_docker_nightly
