name: "Release Pipeline for Pg Auto Failover"
pr: none
trigger:
  - none
jobs:

  - job: Release
    strategy:
      maxParallel: 5
      matrix:
        el8:
          TARGET_PLATFORM: el/8
          PACKAGECLOUD_API_TOKEN: cf058e6c1453b02742cae518499e80dd13a3e9a0893509fd
          REPO_NAME: sample
          PKG_REPOTYPE: community
          GITHUB_TOKEN: 43106393b6ae2f6bd6323e605c2e7be70bce2144
          TRAVIS: true
        el7:
          TARGET_PLATFORM: el/7
          PACKAGECLOUD_API_TOKEN: cf058e6c1453b02742cae518499e80dd13a3e9a0893509fd
          REPO_NAME: sample
          PKG_REPOTYPE: community
          GITHUB_TOKEN: 43106393b6ae2f6bd6323e605c2e7be70bce2144
          TRAVIS: true
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: sudo apt install software-properties-common && sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt install python3.9 && python3.9 --version && sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
      - script: python --version &&  git clone --single-branch --branch pg_auto_failover_build https://github.com/citusdata/tools.git && sudo make -C tools install 
      - script: build_new_release
      - script: pwd && ls && python ./tools/travis/upload_to_package_cloud.py $(TARGET_PLATFORM) $(PACKAGECLOUD_API_TOKEN)  $(REPO_NAME)