name: "Release Pipeline for Pg Auto Failover"
pr: none
trigger:
  - none
variables:
- name: REPO_NAME
  value: sample
- name: PKG_REPOTYPE
  value: community
- name: TRAVIS
  value: true

jobs:

  - job: Release
    strategy:
      maxParallel: 5
      matrix:
        el8:
          TARGET_PLATFORM: el/8

    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo ${GITHUB_TOKEN} && sudo apt install software-properties-common && sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt install python3.9 && python3.9 --version && sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
      - script: python --version &&  git clone --single-branch --branch pg_auto_failover_build https://github.com/citusdata/tools.git && sudo make -C tools install 
      - script: build_new_release
        env:
          GITHUB_TOKEN: $(GITHUB_TOKEN)
          PACKAGECLOUD_API_TOKEN: $(PACKAGECLOUD_API_TOKEN)
      - script: chmod +x ./signed-packages && ./tools/travis/add_test_prefix_on_filenames.sh && chmod +x ./tools/travis/configure_microsoft_packages.sh
      - script: mkdir signed-packages && cp -R ./pkgs/releases/. ./signed-packages && ./tools/travis/add_test_prefix_on_filenames.sh && ./tools/travis/configure_microsoft_packages.sh && ./tools/travis/publish_packages.py
      