# This is a basic workflow to help you get started with Actions

name: Test Multiple Jobs


# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the gindibay-test-release branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    steps:

      - name: Build New Release
        run: exit 1
  build2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    steps:

      - name: Build New Release
        run: exit 0

